[package]
name = "wta-reactor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
pin-project = "1.0"
mio = { version = "0.8", features = ["os-poll", "net"] }
chashmap = "2.2.2"

[dependencies.educe]
version = "*"
features = ["Default", "PartialEq", "Eq", "PartialOrd", "Ord"]
default-features = false
